### ISSUE TITLE
Improvement request:  Dump processed output from file to screen if no -o/-O is specified

### ISSUE THREAD

**Issue by ryanwelsh** [wirebandit/pparse#1]
# Problem Statement
There does not appear to be a way to input from file and output to screen.

Right now, the correct way to output to screen, I _must_ use the `-b` switch and then paste the _content_ of the file into the command.  Which can be unwieldy with a large file.

# Repro
1. Prepare a file that contains encoded URLs: _`pparsetest.txt`_.
2. Invoke `pparse` from that file, do not specify output file because we want it to output to screen:  `pparse -f pparsetest.txt`

## Expected Behavior
* No output file is specified with `-o` or `-O`, so the processed input outputs to screen.

## Actual Behavior
* If I use pparse without a `-o` or `-O`, I get an error:

```
$ pparse -f pparsetest.txt
Must use -o or -O with -f
```

# Suggested Improvement/Solution
What would be nice is the ability to do as I did above, but when the lack of `-o` or `-O` is detected, the script simply accepts that command and treats it as a `-b` from file, outputting the processed input directly to screen.

This may even simplify and obsolete the need for `-o` and `-O`, since the user can always redirect the screen output to file natively using `> pparsetest-output.txt` at the end of the command.  (But I get that some people will prefer having a built-in output option without redirecting the screen output.)

**Comment by wirebandit** [comment]
Excellent catch! Ill work on this @ryanwelsh
